export const WEAPONS = [
  {
    id: "rifle",
    priority: 30,
    name: "M4 / ASSAULT RIFLE",
    mag: 24,
    reload: 1.25,
    cool: 0.115,
    damage: 43,
    speed: 45,
    life: 1.05,
    pellets: 1,
    spread: 0,
    visual: "tracer",
    splash: 0,
  },
  {
    id: "shotgun",
    priority: 20,
    name: "M870 / SCATTERGUN",
    mag: 6,
    reload: 1.7,
    cool: 0.467,
    damage: 28,
    speed: 45,
    life: 0.42,
    pellets: 5,
    spread: 0.085,
    visual: "tracer",
    splash: 0,
  },
  {
    id: "machineGun",
    priority: 80,
    name: "M249 / MACHINE GUN",
    mag: 120,
    reload: 2.4,
    cool: 0.0305,
    damage: 15,
    speed: 49,
    life: 0.75,
    pellets: 1,
    spread: 0.045,
    visual: "tracer",
    splash: 0,
  },
  {
    id: "sniper",
    priority: 70,
    name: "M24 / SNIPER",
    mag: 5,
    reload: 2,
    cool: 0.697,
    damage: 173,
    speed: 100,
    life: 0.6,
    pellets: 1,
    spread: 0,
    visual: "sniper",
    splash: 0,
  },
  {
    id: "flame",
    priority: 50,
    name: "FLAMETHROWER",
    mag: 50,
    reload: 2,
    cool: 0.082,
    damage: 15,
    speed: 18,
    life: 0.38,
    pellets: 3,
    spread: 0.12,
    visual: "flame",
    splash: 0,
  },
  {
    id: "launcher",
    priority: 60,
    name: "GRENADE LAUNCHER",
    mag: 4,
    reload: 2,
    cool: 0.615,
    damage: 107,
    speed: 22,
    life: 1.1,
    pellets: 1,
    spread: 0,
    visual: "grenade",
    splash: 2.5,
  },
  {
    id: "explosiveArrow",
    priority: 55,
    name: "EXPLOSIVE BOW",
    mag: 1,
    reload: 0.7,
    cool: 0.574,
    damage: 82,
    speed: 33,
    life: 1.1,
    pellets: 1,
    spread: 0,
    visual: "arrow",
    splash: 2.8,
  },
  {
    id: "missile",
    priority: 90,
    name: "ANTI-ARMOR MISSILE",
    mag: 1,
    reload: 2.2,
    cool: 0.82,
    damage: 206,
    speed: 24,
    life: 1.7,
    pellets: 1,
    spread: 0,
    visual: "rocket",
    splash: 3.2,
  },
  {
    id: "laser",
    priority: 100,
    name: "HELIX / LASER",
    mag: 8,
    reload: 2,
    cool: 0.533,
    damage: 132,
    speed: 0,
    life: 0,
    pellets: 1,
    spread: 0,
    visual: "laser",
    splash: 0,
  },
  {
    id: "throwBomb",
    priority: 40,
    name: "FRAGMENTATION GRENADE",
    mag: 1,
    reload: 0.8,
    cool: 0.697,
    damage: 107,
    speed: 15,
    life: 0.85,
    pellets: 1,
    spread: 0,
    visual: "grenade",
    splash: 3,
  },
  {
    id: "poisonBomb",
    priority: 10,
    name: "GAS GRENADE",
    mag: 1,
    reload: 0.9,
    cool: 0.82,
    damage: 16,
    speed: 15,
    life: 0.85,
    pellets: 1,
    spread: 0,
    visual: "gas",
    splash: 2.8,
  },
] as const;
export type WeaponSpec = (typeof WEAPONS)[number];
export const VEHICLES = {
  motorcycle: {
    name: "MOTORCYCLE",
    speed: 12,
    accel: 18,
    radius: 0.85,
    hp: 75,
    scale: 0.8,
    ammo: 0,
    weapon: 0,
  },
  jeep: {
    name: "JEEP",
    speed: 9,
    accel: 11,
    radius: 1.65,
    hp: 200,
    scale: 0.72,
    ammo: 20,
    weapon: 1,
  },
  tank: {
    name: "TANK",
    speed: 5.3,
    accel: 7,
    radius: 2.3,
    hp: 1680,
    scale: 0.72,
    ammo: 6,
    weapon: 7,
  },
} as const;
export type VehicleKind = keyof typeof VEHICLES;
