export const WEAPONS = [
  {
    id: "rifle",
    name: "M4 / ASSAULT RIFLE",
    mag: 24,
    reload: 1.25,
    cool: 0.14,
    damage: 26,
    speed: 45,
    life: 1.05,
    pellets: 1,
    spread: 0,
    visual: "tracer",
    splash: 0,
  },
  {
    id: "shotgun",
    name: "M870 / SCATTERGUN",
    mag: 6,
    reload: 1.7,
    cool: 0.57,
    damage: 17,
    speed: 45,
    life: 0.42,
    pellets: 5,
    spread: 0.085,
    visual: "tracer",
    splash: 0,
  },
  {
    id: "machineGun",
    name: "M249 / MACHINE GUN",
    mag: 60,
    reload: 2.4,
    cool: 0.075,
    damage: 18,
    speed: 49,
    life: 0.75,
    pellets: 1,
    spread: 0.045,
    visual: "tracer",
    splash: 0,
  },
  {
    id: "sniper",
    name: "M24 / SNIPER",
    mag: 5,
    reload: 2,
    cool: 0.85,
    damage: 105,
    speed: 100,
    life: 0.6,
    pellets: 1,
    spread: 0,
    visual: "sniper",
    splash: 0,
  },
  {
    id: "flame",
    name: "FLAMETHROWER",
    mag: 50,
    reload: 2,
    cool: 0.1,
    damage: 9,
    speed: 18,
    life: 0.38,
    pellets: 3,
    spread: 0.12,
    visual: "flame",
    splash: 0,
  },
  {
    id: "launcher",
    name: "GRENADE LAUNCHER",
    mag: 4,
    reload: 2,
    cool: 0.75,
    damage: 65,
    speed: 22,
    life: 1.1,
    pellets: 1,
    spread: 0,
    visual: "grenade",
    splash: 2.5,
  },
  {
    id: "explosiveArrow",
    name: "EXPLOSIVE BOW",
    mag: 1,
    reload: 0.7,
    cool: 0.7,
    damage: 50,
    speed: 33,
    life: 1.1,
    pellets: 1,
    spread: 0,
    visual: "arrow",
    splash: 2.8,
  },
  {
    id: "missile",
    name: "ANTI-ARMOR MISSILE",
    mag: 1,
    reload: 2.2,
    cool: 1.0,
    damage: 125,
    speed: 24,
    life: 1.7,
    pellets: 1,
    spread: 0,
    visual: "rocket",
    splash: 3.2,
  },
  {
    id: "laser",
    name: "HELIX / LASER",
    mag: 8,
    reload: 2,
    cool: 0.65,
    damage: 80,
    speed: 0,
    life: 0,
    pellets: 1,
    spread: 0,
    visual: "laser",
    splash: 0,
  },
  {
    id: "throwBomb",
    name: "FRAGMENTATION GRENADE",
    mag: 1,
    reload: 0.8,
    cool: 0.85,
    damage: 65,
    speed: 15,
    life: 0.85,
    pellets: 1,
    spread: 0,
    visual: "grenade",
    splash: 3,
  },
  {
    id: "poisonBomb",
    name: "GAS GRENADE",
    mag: 1,
    reload: 0.9,
    cool: 1,
    damage: 10,
    speed: 15,
    life: 0.85,
    pellets: 1,
    spread: 0,
    visual: "gas",
    splash: 2.8,
  },
] as const;
export type WeaponSpec = (typeof WEAPONS)[number];
export const VEHICLES = {
  motorcycle: {
    name: "MOTORCYCLE",
    speed: 12,
    accel: 18,
    radius: 0.85,
    hp: 75,
    scale: 0.8,
    ammo: 0,
    weapon: 0,
  },
  jeep: {
    name: "JEEP",
    speed: 9,
    accel: 11,
    radius: 1.65,
    hp: 200,
    scale: 0.72,
    ammo: 20,
    weapon: 1,
  },
  tank: {
    name: "TANK",
    speed: 5.3,
    accel: 7,
    radius: 2.3,
    hp: 420,
    scale: 0.72,
    ammo: 5,
    weapon: 7,
  },
} as const;
export type VehicleKind = keyof typeof VEHICLES;
